namespace BerriesParadise.Content.Catalogs;

public class LocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["ES"] = new()
        {
            // Navigation
            ["nav.products"] = "Productos",
            ["nav.quality"] = "Excelencia y calidad",
            ["nav.process"] = "Del campo al mundo",
            ["nav.genetics"] = "Genética",
            ["nav.inspiration"] = "Inspiración",
            ["nav.contact"] = "Contacto",
            ["nav.productos"] = "Productos",
            ["nav.calidad"] = "Excelencia y calidad",
            ["nav.proceso"] = "Del campo al mundo",
            ["nav.genetica"] = "Genética",
            ["nav.inspiracion"] = "Inspiración",
            ["nav.contacto"] = "Contacto",
            ["nav.cta"] = "Contactar ventas",
            ["nav.search"] = "Buscar en catálogo",

            // Hero
            ["hero.eyebrow"] = "FUTUROS MÁS FRESCOS",
            ["hero.title1"] = "BERRIES",
            ["hero.title2"] = "CULTIVADAS CON",
            ["hero.title3"] = "PROPÓSITO.",
            ["hero.description"] = "Berries selectas para un mundo más saludable, lleno de sabor y sustentable.",
            ["hero.btnExplore"] = "EXPLORAR PRODUCTOS",
            ["hero.btnStory"] = "CONOCE NUESTRA HISTORIA",
            ["hero.btnVideo"] = "VER VIDEO",

            // Berries Section
            ["berries.kicker"] = "PORTAFOLIO FRESCO & SUSTENTABLE",
            ["berries.title1"] = "NUESTRAS",
            ["berries.title2"] = "BERRIES",
            ["berries.subtitle"] = "Un portafolio fresco, versátil y lleno de sabor.",
            ["berries.btnPortfolio"] = "Ver portafolio",
            ["berries.btnMore"] = "Conocer más",
            ["berries.badge"] = "Variedad Selecta",
            ["berries.availability"] = "Disponibilidad",
            ["berries.benefit"] = "Beneficio Destacado",
            ["berries.btnSheet"] = "Ficha Técnica Completa",

            // Fruits
            ["fruit.arandanos"] = "Arándanos",
            ["fruit.frambuesas"] = "Frambuesas",
            ["fruit.zarzamoras"] = "Zarzamoras",
            ["fruit.fresas"] = "Fresas",
            ["fruit.all"] = "Todas",

            // Fruit Details
            ["berry.arandanos.name"] = "Arándanos",
            ["berry.arandanos.desc"] = "Fruta firme, con sabor equilibrado, textura increíble, floración cerosa natural (bloom) y calidad constante durante todo el año.",
            ["berry.arandanos.season"] = "Producción continua 52 semanas al año",
            ["berry.arandanos.health"] = "Rico en antocianinas, flavonoides bioactivos, vitamina C (16% IDR), vitamina K (36% IDR) y manganeso esencial para la salud celular.",
            ["berry.arandanos.c1"] = "Calibres estándar a Jumbo (14mm - 26mm)",
            ["berry.arandanos.c2"] = "Bloom natural protector intacto",
            ["berry.arandanos.c3"] = "Firmeza superior a 220 g/mm",
            ["berry.arandanos.c4"] = "Brix equilibrado 12.0° - 15.5°",

            ["berry.frambuesas.name"] = "Frambuesas",
            ["berry.frambuesas.desc"] = "El balance perfecto de color rojo rubí, textura aterciopelada y un sabor delicado para darte un fruto naturalmente versátil y aromático.",
            ["berry.frambuesas.season"] = "Septiembre a Junio (Pico en invierno y primavera)",
            ["berry.frambuesas.health"] = "Extraordinaria fuente de fibra dietética (8g por taza), ácido elágico, vitamina C (54% IDR) y antioxidantes que protegen la salud cardiovascular.",
            ["berry.frambuesas.c1"] = "Receptáculo cerrado resistente",
            ["berry.frambuesas.c2"] = "Color rojo rubí brillante",
            ["berry.frambuesas.c3"] = "Acidez equilibrada con dulzor natural",
            ["berry.frambuesas.c4"] = "Vida de anaquel refrigerada hasta 18 días",

            ["berry.zarzamoras.name"] = "Zarzamoras",
            ["berry.zarzamoras.desc"] = "Sabor intenso, drupas carnosas con brillo negro profundo y frescura insuperable para recetas gourmet, snacks saludables y consumo diario.",
            ["berry.zarzamoras.season"] = "Octubre a Mayo",
            ["berry.zarzamoras.health"] = "Excelente aporte de vitamina C, vitamina K, folato y luteína para la protección ocular y el refuerzo del sistema inmune.",
            ["berry.zarzamoras.c1"] = "Variedades cultivadas 100% sin espinas",
            ["berry.zarzamoras.c2"] = "Nula reversión a rojo (red drupelet)",
            ["berry.zarzamoras.c3"] = "Dulzura pura sin amargor",
            ["berry.zarzamoras.c4"] = "Calibre grande y uniforme",

            ["berry.fresas.name"] = "Fresas",
            ["berry.fresas.desc"] = "Una fruta familiar, vibrante, con aroma penetrante y dulzor natural cosechada en su punto óptimo de maduración para deleitar a familias enteras.",
            ["berry.fresas.season"] = "Noviembre a Mayo",
            ["berry.fresas.health"] = "Aporta más del 140% de la ingesta diaria recomendada de vitamina C por porción, promoviendo la producción de colágeno y vitalidad.",
            ["berry.fresas.c1"] = "Forma cónica homogénea",
            ["berry.fresas.c2"] = "Rojo carmesí de corazón a piel",
            ["berry.fresas.c3"] = "Brillo natural sin ceras químicas",
            ["berry.fresas.c4"] = "Calibre selecto para retail",

            // Products Section
            ["product.kicker"] = "PORTAFOLIO DE PRODUCTOS",
            ["product.title1"] = "NUESTRO PORTAFOLIO,",
            ["product.title2"] = "NUESTRAS BERRIES.",
            ["product.subtitle"] = "Descubre nuestro portafolio de berries y las diferentes líneas que desarrollamos para cada mercado.",
            ["product.size"] = "Mayor tamaño",
            ["product.flavor"] = "Sabor excepcional",
            ["product.pack"] = "Presentación premium",
            ["product.btnMore"] = "CONOCE MÁS",
            ["product.featuredVarieties"] = "VARIEDADES DESTACADAS",
            ["product.linePrefix"] = "Línea",
            ["product.countOption"] = "opción",
            ["product.countLines"] = "líneas",
            ["product.quickView"] = "Ver detalles comerciales",

            // Product Lines
            ["line.clasica"] = "Clásica",
            ["line.big-delight"] = "Big Delight",
            ["line.organica"] = "Orgánica",
            ["line.legacy"] = "Legacy",
            ["line.legacy-jumbo"] = "Legacy Jumbo Blues",

            // Products data
            ["prod.clasica-arandanos.desc"] = "Fruta firme, con sabor equilibrado, textura increíble y calidad constante durante todo el año.",
            ["prod.clasica-arandanos.size"] = "Calibre uniforme (14mm - 16mm)",
            ["prod.clasica-arandanos.flavor"] = "Sabor equilibrado",
            ["prod.clasica-arandanos.pack"] = "Presentación clamshell retail",
            ["prod.clasica-arandanos.shelf"] = "21 días refrigerada",

            ["prod.big-delight-arandanos.desc"] = "Una experiencia de mayor tamaño, presencia y detalle. Blueberries seleccionadas para quienes buscan algo más especial.",
            ["prod.big-delight-arandanos.size"] = "Mayor tamaño (18mm - 24mm)",
            ["prod.big-delight-arandanos.flavor"] = "Sabor excepcional dulce y aromático",
            ["prod.big-delight-arandanos.pack"] = "Presentación premium rPET 100% reciclable",
            ["prod.big-delight-arandanos.shelf"] = "24 días refrigerada",

            ["prod.clasica-frambuesas.desc"] = "El balance perfecto de color, textura y un sabor delicado para darte un fruto naturalmente versátil.",
            ["prod.clasica-frambuesas.size"] = "Calibre estándar (14mm - 16mm)",
            ["prod.clasica-frambuesas.flavor"] = "Sabor delicado agridulce",
            ["prod.clasica-frambuesas.pack"] = "Clamshell 170g ventilado",
            ["prod.clasica-frambuesas.shelf"] = "14 días refrigerada",

            ["prod.clasica-zarzamoras.desc"] = "Sabor intenso, apariencia profunda y frescura para recetas, snacks y consumo diario.",
            ["prod.clasica-zarzamoras.size"] = "Calibre estándar (15mm - 18mm)",
            ["prod.clasica-zarzamoras.flavor"] = "Sabor intenso y frutal",
            ["prod.clasica-zarzamoras.pack"] = "Clamshell 170g / 340g",
            ["prod.clasica-zarzamoras.shelf"] = "15 días refrigerada",

            ["prod.clasica-fresas.desc"] = "Una fruta familiar, vibrante y naturalmente dulce para compartir en familia.",
            ["prod.clasica-fresas.size"] = "Calibre uniforme mediano a grande",
            ["prod.clasica-fresas.flavor"] = "Naturalmente dulce y fragante",
            ["prod.clasica-fresas.pack"] = "Clamshell 454g (1 lb) y 907g (2 lb)",
            ["prod.clasica-fresas.shelf"] = "12 días refrigerada",

            ["prod.organica-arandanos.desc"] = "Cosechadas sin químicos sintéticos, con prácticas que cuidan la tierra y respetan los ciclos de la naturaleza.",
            ["prod.organica-arandanos.size"] = "Calibre orgánico certificado",
            ["prod.organica-arandanos.flavor"] = "Dulzura pura natural",
            ["prod.organica-arandanos.pack"] = "Clamshell rPET 100% reciclable",
            ["prod.organica-arandanos.shelf"] = "20 días refrigerada",

            ["prod.organica-frambuesas.desc"] = "Cosechadas sin químicos sintéticos, con prácticas que cuidan el suelo y respetan los ciclos de la naturaleza.",
            ["prod.organica-frambuesas.size"] = "Calibre premium (16mm+)",
            ["prod.organica-frambuesas.flavor"] = "Dulzura silvestre pura",
            ["prod.organica-frambuesas.pack"] = "Bio-Pack de fibra compostable",
            ["prod.organica-frambuesas.shelf"] = "16 días refrigerada",

            ["prod.organica-zarzamoras.desc"] = "Cosechadas sin químicos sintéticos, con prácticas que cuidan el suelo y respetan los ciclos de la naturaleza.",
            ["prod.organica-zarzamoras.size"] = "Calibre orgánico selecto",
            ["prod.organica-zarzamoras.flavor"] = "Notas frutales profundas",
            ["prod.organica-zarzamoras.pack"] = "Clamshell reciclable ventilado",
            ["prod.organica-zarzamoras.shelf"] = "15 días refrigerada",

            ["prod.legacy-arandanos.desc"] = "Nuestra oferta más exclusiva: berries con una genética superior que brindan un sabor más intenso y consistente, un color más profundo y una firmeza perfecta.",
            ["prod.legacy-arandanos.size"] = "Genética superior seleccionada",
            ["prod.legacy-arandanos.flavor"] = "Sabor más intenso y consistente",
            ["prod.legacy-arandanos.pack"] = "Presentación exclusiva Legacy",
            ["prod.legacy-arandanos.shelf"] = "25 días refrigerada",

            ["prod.legacy-jumbo.desc"] = "La experiencia superior de Legacy en arándanos jumbo, combinando calibres superiores a 22mm con crocancia inolvidable.",
            ["prod.legacy-jumbo.size"] = "Calibre colosal (> 22mm)",
            ["prod.legacy-jumbo.flavor"] = "Dulzura concentrada con pop acústico",
            ["prod.legacy-jumbo.pack"] = "Clamshell premium ventilado",
            ["prod.legacy-jumbo.shelf"] = "28 días refrigerada",

            // Genetics Section
            ["genetics.kicker"] = "PROGRAMA VARIETAL PATENTADO",
            ["genetics.title1"] = "GENÉTICA",
            ["genetics.title2"] = "PREMIUM",
            ["genetics.subtitle"] = "Detrás de cada berry hay obsesión por los detalles: desde la elección de genéticas superiores hasta la cosecha a mano para darte frutos simplemente perfectos.",
            ["genetics.btnCatalog"] = "Explorar catálogo varietal",
            ["genetics.registered"] = "VARIEDAD REGISTRADA",
            ["genetics.btnSheet"] = "Ver ficha técnica",
            ["genetics.sheetTitle"] = "Ficha Técnica Agronómica",
            ["genetics.specCaliber"] = "Calibre",
            ["genetics.specBrix"] = "Dulzura Brix",
            ["genetics.specFirmness"] = "Firmeza",
            ["genetics.specShelf"] = "Vida en Anaquel",
            ["genetics.specHarvest"] = "Ventana Cosecha",
            ["genetics.specLicensing"] = "Licenciamiento",
            ["genetics.btnInquire"] = "Solicitar Programa de Cosecha",
            ["genetics.type.raspberry"] = "Frambuesa",
            ["genetics.type.blackberry"] = "Zarzamora",
            ["genetics.type.blueberry"] = "Arándano",
            ["genetics.type.strawberry"] = "Fresa",

            ["genetics.amalia.desc"] = "Variedad registrada con maduración homogénea que garantiza lotes uniformes para exportación de calidad superior. Su receptáculo cerrado evita el colapso poscosecha.",
            ["genetics.amalia.t1"] = "Madurez uniforme",
            ["genetics.amalia.t2"] = "Calibre consistente",
            ["genetics.amalia.t3"] = "Bajo chill requerido",
            ["genetics.amalia.t4"] = "Alta tasa de exportación",
            ["genetics.amalia.shelf"] = "18+ días",
            ["genetics.amalia.harvest"] = "Octubre - Mayo",
            ["genetics.amalia.license"] = "Patente Exclusiva Berries Paradise",

            ["genetics.erendira.desc"] = "Variedad mexicana de alto rendimiento, desarrollada para condiciones climáticas locales con excelente perfil organoléptico y plantas libres de espinas.",
            ["genetics.erendira.t1"] = "Resistencia climática",
            ["genetics.erendira.t2"] = "Cosecha extendida",
            ["genetics.erendira.t3"] = "Perfil aromático único",
            ["genetics.erendira.t4"] = "Adaptabilidad regional",
            ["genetics.erendira.shelf"] = "20+ días",
            ["genetics.erendira.harvest"] = "Noviembre - Junio",
            ["genetics.erendira.license"] = "Variedad Protegida Nacional",

            ["genetics.sekoya-beauty.desc"] = "Arándano de belleza excepcional con bloom natural preservado, textura crocante y calibre jumbo persistente, ideal para presentación en retail premium internacional.",
            ["genetics.sekoya-beauty.t1"] = "Color azul intenso",
            ["genetics.sekoya-beauty.t2"] = "Bloom perfecto",
            ["genetics.sekoya-beauty.t3"] = "Firmeza superior",
            ["genetics.sekoya-beauty.t4"] = "Versatilidad culinaria",
            ["genetics.sekoya-beauty.shelf"] = "25+ días",
            ["genetics.sekoya-beauty.harvest"] = "Septiembre - Marzo",
            ["genetics.sekoya-beauty.license"] = "Sekoya™ Club Member Variety",

            ["genetics.sekoya-pop.desc"] = "Variedad premium de arándanos desarrollada para mercados de alta exigencia, con equilibrio óptimo entre dulzura y acidez, y su célebre 'pop' acústico al morder.",
            ["genetics.sekoya-pop.t1"] = "Sabor excepcional",
            ["genetics.sekoya-pop.t2"] = "Tamaño uniforme",
            ["genetics.sekoya-pop.t3"] = "Larga vida de anaquel",
            ["genetics.sekoya-pop.t4"] = "Alta productividad",
            ["genetics.sekoya-pop.shelf"] = "30+ días",
            ["genetics.sekoya-pop.harvest"] = "Noviembre - Mayo",
            ["genetics.sekoya-pop.license"] = "Sekoya™ Club Member Variety",

            // Field to World
            ["field.kicker"] = "TRAZABILIDAD INTEGRAL DE ORIGEN",
            ["field.title1"] = "DEL CAMPO",
            ["field.title2"] = "AL MUNDO",
            ["field.subtitle"] = "Un proceso exigente que garantiza frescura, calidad y consistencia en cada etapa.",
            ["field.btnProtocols"] = "Consultar Protocolos de Inocuidad",
            ["field.stage"] = "ETAPA",
            ["field.btnVideo"] = "Ver Video de Origen",

            ["field.step.1.title"] = "Cultivo",
            ["field.step.1.sub"] = "Nutrición vegetal de precisión y microclimas ideales",
            ["field.step.1.desc"] = "Campos ubicados en valles protegidos de Jalisco y Michoacán a más de 1,500 msnm. Riego computarizado por goteo, nutrición orgánica balanceada y polinización natural por abejorros nativos.",
            ["field.step.1.high"] = "100% agua de pozo profundo analizada",
            ["field.step.1.temp"] = "18°C - 24°C ambiental",

            ["field.step.2.title"] = "Cosecha",
            ["field.step.2.sub"] = "Cosecha manual experta al alba",
            ["field.step.2.desc"] = "Cosechada a mano en las primeras horas frescas de la mañana cuando la fruta mantiene su turgencia natural. Se sujeta cuidadosamente del pedúnculo para no alterar la capa cerosa protectora (bloom).",
            ["field.step.2.high"] = "Recolección artesanal 100% a mano",
            ["field.step.2.temp"] = "12°C - 16°C matutino",

            ["field.step.3.title"] = "Selección y empaque",
            ["field.step.3.sub"] = "Clasificación óptica espectral y salas limpias",
            ["field.step.3.desc"] = "En salas con aire filtrado y presión positiva, cámaras espectrales de visión computarizada 360° analizan calibre milimétrico, colorimetría, brix y textura a velocidades de hasta 12 toneladas por hora.",
            ["field.step.3.high"] = "Visión computarizada espectral 360°",
            ["field.step.3.temp"] = "10°C en salas de empaque",

            ["field.step.4.title"] = "Cadena de frío",
            ["field.step.4.sub"] = "Túneles de choque térmico por aire forzado",
            ["field.step.4.desc"] = "En menos de 60 minutos desde el corte, la fruta entra a túneles de aire forzado reduciendo el calor metabólico de campo a 1.5°C exactos, sellando los azúcares naturales y frenando el envejecimiento celular.",
            ["field.step.4.high"] = "Reducción térmica a 1.5°C en < 60 min",
            ["field.step.4.temp"] = "1.0°C - 2.0°C ininterrumpida",

            ["field.step.5.title"] = "Al mundo",
            ["field.step.5.sub"] = "Logística multimodal express terrestre y aérea",
            ["field.step.5.desc"] = "Despachos directos refrigerados a más de 19 países. Rutas terrestres express hacia Estados Unidos y Canadá, y vuelos de carga directa hacia Europa, Japón, Singapur y Emiratos Árabes.",
            ["field.step.5.high"] = "Llegada a anaquel internacional en < 48 hrs",
            ["field.step.5.temp"] = "Cadena de frío continua a 1.5°C",

            // Quality Section
            ["quality.kicker"] = "CIENCIA AGRÍCOLA & CADENA DE FRÍO",
            ["quality.title1"] = "EXCELENCIA",
            ["quality.title2"] = "Y CALIDAD",
            ["quality.subtitle"] = "Control milimétrico desde la polinización hasta el anaquel de destino.",
            ["quality.cert"] = "Certificación PrimusGFS",
            ["quality.certSub"] = "Auditorías Grado AA Global",
            ["quality.btnTech"] = "Ficha Técnica de Calidad",
            ["quality.controlStandard"] = "Estándar de Control",
            ["quality.thermalParam"] = "Parámetro Térmico",
            ["quality.btnHarvestTimeline"] = "Ver Cronología de Cosecha",
            ["quality.capacity"] = "Capacidad:",
            ["quality.temperature"] = "Temperatura:",
            ["quality.processOf"] = "PROCESO {0} DE 05",
            ["quality.btnCert"] = "Consultar Certificaciones de Inocuidad",

            ["quality.fac.1.title"] = "Campo",
            ["quality.fac.1.sub"] = "Valles Fértiles",
            ["quality.fac.1.desc"] = "Más de 3,000 hectáreas de macrotúneles y casas sombra con monitoreo climático satelital y estaciones meteorológicas propias.",
            ["quality.fac.1.high"] = "3,000+ Hectáreas",
            ["quality.fac.1.temp"] = "Ambiente",

            ["quality.fac.2.title"] = "Preenfriado",
            ["quality.fac.2.sub"] = "Túneles de Choque",
            ["quality.fac.2.desc"] = "Túneles de preenfriado por aire forzado a contracorriente con humedad relativa controlada al 95%.",
            ["quality.fac.2.high"] = "80 Tons / Turno",
            ["quality.fac.2.temp"] = "1.5°C",

            ["quality.fac.3.title"] = "Selección y empaque",
            ["quality.fac.3.sub"] = "Líneas Automatizadas",
            ["quality.fac.3.desc"] = "Líneas de selección óptica automatizadas con cámaras multiespectrales para evaluación de defectos microscópicos.",
            ["quality.fac.3.high"] = "120 Tons / Día",
            ["quality.fac.3.temp"] = "10°C",

            ["quality.fac.4.title"] = "Almacenamiento",
            ["quality.fac.4.sub"] = "Cámaras Inteligentes",
            ["quality.fac.4.desc"] = "Cámaras de frío con control de etileno y atmósfera ozonificada para prolongar la vitalidad de la fruta.",
            ["quality.fac.4.high"] = "500 Pallets estáticos",
            ["quality.fac.4.temp"] = "1.0°C - 1.5°C",

            ["quality.fac.5.title"] = "Envío",
            ["quality.fac.5.sub"] = "Flota Refrigerada",
            ["quality.fac.5.desc"] = "Camiones inteligentes y contenedores refrigerados conectados a la nube con alertas de variación de 0.5°C.",
            ["quality.fac.5.high"] = "40+ Cargas Diarias",
            ["quality.fac.5.temp"] = "1.5°C",

            // Recipes Section
            ["recipes.kicker"] = "INSPIRACIÓN",
            ["recipes.title1"] = "RECETAS",
            ["recipes.title2"] = "CON BERRIES",
            ["recipes.subtitle"] = "\"Esponjosos, llenos de sabor y con el balance perfecto entre dulzura y frescura.\"",
            ["recipes.btnAll"] = "VER TODAS LAS RECETAS",
            ["recipes.editorial"] = "EDITORIAL GASTRONÓMICO",
            ["recipes.btnView"] = "VER RECETA",
            ["recipes.servings"] = "Porciones",
            ["recipes.persons"] = "personas",
            ["recipes.calories"] = "Calorías",
            ["recipes.ingredients"] = "Ingredientes",
            ["recipes.freshItems"] = "items frescos",
            ["recipes.freshIngredients"] = "Ingredientes Frescos",
            ["recipes.prep"] = "Prep",
            ["recipes.cook"] = "Cocción",
            ["recipes.stepByStep"] = "Paso a Paso",
            ["recipes.btnReady"] = "¡Listo para cocinar!",
            ["recipes.prev"] = "Receta anterior",
            ["recipes.next"] = "Receta siguiente",

            ["recipe.pancakes-berries-mixtos.title"] = "Pancakes de Berries Mixtos",
            ["recipe.pancakes-berries-mixtos.cat"] = "Desayuno",
            ["recipe.pancakes-berries-mixtos.desc"] = "Esponjosos, llenos de sabor y con el balance perfecto entre dulzura y frescura. Coronado con frutos recién cosechados y miel tibia de maple.",

            ["recipe.smoothie-bowl-antioxidante.title"] = "Super Smoothie Bowl de Berries",
            ["recipe.smoothie-bowl-antioxidante.cat"] = "Energía & Salud",
            ["recipe.smoothie-bowl-antioxidante.desc"] = "Un festín concentrado de polifenoles, fibra y antioxidantes naturales para iniciar el día con vitalidad y frescura inigualable.",

            ["recipe.tartaleta-frambuesas-crema-mascarpone.title"] = "Tartaleta de Frambuesas & Mascarpone",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.cat"] = "Repostería Fina",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.desc"] = "Costra sablée crujiente con suave crema batida de mascarpone a la vainilla de Papantla y corona de frambuesas Amalia® recién cortadas.",

            ["recipe.parfait-arandanos-chia-granola.title"] = "Parfait de Chía, Yogur & Arándanos",
            ["recipe.parfait-arandanos-chia-granola.cat"] = "Desayuno Ligero",
            ["recipe.parfait-arandanos-chia-granola.desc"] = "Capas alternadas de pudín de chía hidratado en leche de coco, yogur estilo griego sin azúcar y compota rústica de arándanos jumbo.",

            ["recipe.cheesecake-zarzamora-legacy.title"] = "Cheesecake Horneado con Zarzamora",
            ["recipe.cheesecake-zarzamora-legacy.cat"] = "Postres Gourmet",
            ["recipe.cheesecake-zarzamora-legacy.desc"] = "Cremosa textura horneada lentamente al baño maría cubierta con glaseado brillante de zarzamoras Legacy y notas de limón amarillo.",

            ["recipe.ensalada-fresas-espinaca-queso-cabra.title"] = "Ensalada de Espinaca, Fresas & Nueces",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.cat"] = "Almuerzo Fresco",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.desc"] = "Frescura vibrante de fresas recién fileteadas sobre hojas tiernas de espinaca baby, queso de cabra cenizo y reducción de vinagre balsámico de Módena.",

            ["recipe.muffins-avena-arandanos-limon.title"] = "Muffins Rústicos de Avena & Arándanos",
            ["recipe.muffins-avena-arandanos-limon.cat"] = "Snack Saludable",
            ["recipe.muffins-avena-arandanos-limon.desc"] = "Muffins horneados sin azúcar refinada cargados de arándanos enteros que estallan en el horno brindando dulzura jugosa en cada bocado.",

            ["recipe.galette-rustica-multi-berries.title"] = "Galette Rústica de Tres Berries",
            ["recipe.galette-rustica-multi-berries.cat"] = "Panadería Rústica",
            ["recipe.galette-rustica-multi-berries.desc"] = "Masa hojaldrada abierta y doblada a mano que envuelve una explosión de frambuesas, arándanos y zarzamoras horneadas con azúcar mascabado.",

            // Global Presence
            ["presence.kicker"] = "ALCANCE INTERNACIONAL",
            ["presence.title1"] = "PRESENCIA",
            ["presence.title2"] = "GLOBAL",
            ["presence.subtitle"] = "\"Llevamos berries de la más alta calidad a mercados alrededor del mundo.\"",
            ["presence.btnExport"] = "Programa de Exportación",
            ["presence.skus"] = "SKUs para retail",
            ["presence.skusSub"] = "Formatos clamshell y a granel listos para anaquel",
            ["presence.countries"] = "Países a los que exportamos",
            ["presence.countriesSub"] = "Norteamérica, Europa, Asia-Pacífico y Medio Oriente",
            ["presence.global"] = "Mercados globales",
            ["presence.globalSub"] = "Alianzas comerciales estratégicas en 4 continentes",
            ["presence.markets"] = "Mercados",
            ["map.mexico"] = "MÉXICO",
            ["map.usa_canada"] = "USA & CANADÁ",
            ["map.europe"] = "EUROPA",
            ["map.south_america"] = "SUDAMÉRICA",
            ["map.asia_pacific"] = "ASIA-PACÍFICO",
            ["map.middle_east"] = "MEDIO ORIENTE",

            // Final CTA
            ["cta.kicker"] = "EL CIERRE DE UN VIAJE EXTRAORDINARIO",
            ["cta.title1"] = "LLEVAMOS BERRIES",
            ["cta.title2"] = "DE CALIDAD A TU MERCADO",
            ["cta.subtitle"] = "\"¿Buscas un socio confiable para tu cadena de suministro?\"",
            ["cta.btnProducts"] = "VER PRODUCTOS",
            ["cta.btnSales"] = "CONTACTAR VENTAS",

            // Footer
            ["footer.slogan"] = "Berries Grown with Purpose.",
            ["footer.language"] = "IDIOMA:",
            ["footer.privacy"] = "Aviso de privacidad",
            ["footer.terms"] = "Términos de servicio",
            ["footer.colProducts"] = "PRODUCTOS",
            ["footer.colCompany"] = "EMPRESA",
            ["footer.colHelp"] = "AYUDA",
            ["footer.colSocial"] = "SOCIALES",
            ["footer.blueberries"] = "Arándanos",
            ["footer.raspberries"] = "Frambuesas",
            ["footer.blackberries"] = "Zarzamoras",
            ["footer.strawberries"] = "Fresas",
            ["footer.quality"] = "Excelencia y calidad",
            ["footer.about"] = "Nosotros",
            ["footer.inspiration"] = "Inspiración",
            ["footer.contact"] = "Contacto",
            ["footer.faqs"] = "FAQs",
            ["footer.copyright"] = "©2026 Berries Paradise. Todos los derechos reservados.",

            // Modals General
            ["modal.close"] = "Cerrar",
            ["common.close"] = "Cerrar",
            ["modal.product.size"] = "Mayor tamaño",
            ["modal.product.flavor"] = "Sabor",
            ["modal.product.pack"] = "Presentación",
            ["modal.product.formatsTitle"] = "Formatos Comerciales & Retail",
            ["modal.product.formatsText"] = "Disponible en clamshell de 6 oz, 11 oz, 18 oz y caja master para exportación aérea y marítima refrigerada con atmósfera controlada.",
            ["modal.product.disclaimer"] = "Disponibilidad para importación internacional",
            ["modal.product.btnQuote"] = "Cotizar este producto",

            ["modal.berry.nutritionTitle"] = "Perfil Nutricional & Salud",
            ["modal.berry.seasonLabel"] = "Temporada:",
            ["modal.berry.qualityTitle"] = "Estándares y Atributos de Calidad",
            ["modal.berry.btnQuote"] = "Cotizar Programa Retail",

            ["modal.contact.title"] = "Contactar a Ventas & Distribución",
            ["modal.contact.titleMain"] = "Contactar a",
            ["modal.contact.titleHighlight"] = "Ventas & Distribución",
            ["modal.contact.subtitle"] = "Conéctate directamente con nuestro equipo de exportación para programas retail, mayoreo y abasto internacional.",
            ["modal.contact.fullName"] = "Nombre Completo *",
            ["modal.contact.placeholderName"] = "Ej. Roberto Mendoza",
            ["modal.contact.company"] = "Empresa / Retailer *",
            ["modal.contact.placeholderCompany"] = "Ej. Whole Foods / Walmart",
            ["modal.contact.email"] = "Correo Corporativo *",
            ["modal.contact.destinationCountry"] = "País de Destino *",
            ["modal.contact.productInterest"] = "Producto de Interés",
            ["modal.contact.estimatedVolume"] = "Volumen Estimado",
            ["modal.contact.specs"] = "Especificaciones del Requerimiento",
            ["modal.contact.placeholderSpecs"] = "Especifica calibres, tipo de clamshell o ventana de entrega requerida...",
            ["modal.contact.submit"] = "Enviar Solicitud a Exportaciones",
            ["modal.contact.successTitle"] = "¡Solicitud Recibida!",
            ["modal.contact.successText"] = "Un director comercial de Berries Paradise se pondrá en contacto contigo en menos de 24 horas con nuestro catálogo de cotizaciones y disponibilidad.",
            ["modal.contact.btnReset"] = "Entendido",

            ["modal.video.title"] = "Berries Grown with Purpose: Cosechando el Futuro",
            ["modal.video.desc"] = "Recorrido cinematográfico por nuestros campos protegidos, innovación genética varietal y trazabilidad de frío internacional.",
            ["modal.video.download"] = "Descargar",
            ["modal.video.contact"] = "Contactar Ventas",
            ["modal.video.unmute"] = "Activar Audio",
            ["modal.video.error"] = "No se pudo inicializar la reproducción directa.",
            ["modal.video.newTab"] = "Ver video en nueva pestaña ↗",

            ["modal.search.title"] = "Buscar en Berries Paradise",
            ["modal.search.placeholder"] = "Escribe un producto, genética o receta (ej. Big Delight, Sekoya, Pancakes)...",
            ["modal.search.noResults"] = "No se encontraron resultados para tu búsqueda.",
            ["modal.search.products"] = "Productos",
            ["modal.search.genetics"] = "Genética Varietal",
            ["modal.search.recipes"] = "Recetas"
        },
        ["EN"] = new()
        {
            // Navigation
            ["nav.products"] = "Products",
            ["nav.quality"] = "Excellence & Quality",
            ["nav.process"] = "Field to World",
            ["nav.genetics"] = "Genetics",
            ["nav.inspiration"] = "Inspiration",
            ["nav.contact"] = "Contact",
            ["nav.productos"] = "Products",
            ["nav.calidad"] = "Excellence & Quality",
            ["nav.proceso"] = "Field to World",
            ["nav.genetica"] = "Genetics",
            ["nav.inspiracion"] = "Inspiration",
            ["nav.contacto"] = "Contact",
            ["nav.cta"] = "Contact Sales",
            ["nav.search"] = "Search catalog",

            // Hero
            ["hero.eyebrow"] = "FRESHER TOMORROWS",
            ["hero.title1"] = "BERRIES",
            ["hero.title2"] = "GROWN WITH",
            ["hero.title3"] = "PURPOSE.",
            ["hero.description"] = "Curated berries for a healthier, more flavorful, and sustainable world.",
            ["hero.btnExplore"] = "EXPLORE PRODUCTS",
            ["hero.btnStory"] = "DISCOVER OUR STORY",
            ["hero.btnVideo"] = "WATCH VIDEO",

            // Berries Section
            ["berries.kicker"] = "FRESH & SUSTAINABLE PORTFOLIO",
            ["berries.title1"] = "OUR",
            ["berries.title2"] = "BERRIES",
            ["berries.subtitle"] = "A fresh, versatile portfolio bursting with extraordinary flavor.",
            ["berries.btnPortfolio"] = "View portfolio",
            ["berries.btnMore"] = "Learn more",
            ["berries.badge"] = "Select Variety",
            ["berries.availability"] = "Availability",
            ["berries.benefit"] = "Key Benefit",
            ["berries.btnSheet"] = "Full Technical Sheet",

            // Fruits
            ["fruit.arandanos"] = "Blueberries",
            ["fruit.frambuesas"] = "Raspberries",
            ["fruit.zarzamoras"] = "Blackberries",
            ["fruit.fresas"] = "Strawberries",
            ["fruit.all"] = "All",

            // Fruit Details
            ["berry.arandanos.name"] = "Blueberries",
            ["berry.arandanos.desc"] = "Firm fruit with balanced flavor, incredible texture, intact natural bloom, and year-round consistent quality.",
            ["berry.arandanos.season"] = "Continuous production 52 weeks a year",
            ["berry.arandanos.health"] = "Rich in anthocyanins, bioactive flavonoids, vitamin C (16% DV), vitamin K (36% DV), and cellular health manganese.",
            ["berry.arandanos.c1"] = "Standard to Jumbo calibers (14mm - 26mm)",
            ["berry.arandanos.c2"] = "Intact natural protective bloom",
            ["berry.arandanos.c3"] = "Firmness exceeding 220 g/mm",
            ["berry.arandanos.c4"] = "Balanced Brix 12.0° - 15.5°",

            ["berry.frambuesas.name"] = "Raspberries",
            ["berry.frambuesas.desc"] = "The perfect balance of ruby red color, velvety texture, and delicate aroma for a versatile fruit.",
            ["berry.frambuesas.season"] = "September to June (Peak in winter and spring)",
            ["berry.frambuesas.health"] = "Exceptional source of dietary fiber (8g per cup), ellagic acid, vitamin C (54% DV), and cardiovascular antioxidants.",
            ["berry.frambuesas.c1"] = "Resistant closed receptacle",
            ["berry.frambuesas.c2"] = "Lustrous ruby red color",
            ["berry.frambuesas.c3"] = "Balanced acidity with natural sweetness",
            ["berry.frambuesas.c4"] = "Refrigerated shelf life up to 18 days",

            ["berry.zarzamoras.name"] = "Blackberries",
            ["berry.zarzamoras.desc"] = "Intense flavor, plump drupelets with deep black luster, and unsurpassed freshness for gourmet recipes and healthy snacking.",
            ["berry.zarzamoras.season"] = "October to May",
            ["berry.zarzamoras.health"] = "Excellent source of vitamin C, vitamin K, folate, and lutein for vision support and immune health.",
            ["berry.zarzamoras.c1"] = "100% thornless cultivated varieties",
            ["berry.zarzamoras.c2"] = "Zero red drupelet reversion",
            ["berry.zarzamoras.c3"] = "Pure sweetness without bitterness",
            ["berry.zarzamoras.c4"] = "Large and uniform caliber",

            ["berry.fresas.name"] = "Strawberries",
            ["berry.fresas.desc"] = "A vibrant, familiar fruit with fragrant aroma and natural sweetness harvested at peak ripeness.",
            ["berry.fresas.season"] = "November to May",
            ["berry.fresas.health"] = "Provides over 140% of the recommended daily intake of vitamin C per serving, boosting collagen and vitality.",
            ["berry.fresas.c1"] = "Homogeneous conical shape",
            ["berry.fresas.c2"] = "Crimson red from core to skin",
            ["berry.fresas.c3"] = "Natural shine without chemical waxes",
            ["berry.fresas.c4"] = "Select caliber for premier retail",

            // Products Section
            ["product.kicker"] = "PRODUCT PORTFOLIO",
            ["product.title1"] = "OUR PORTFOLIO,",
            ["product.title2"] = "OUR BERRIES.",
            ["product.subtitle"] = "Discover our berry portfolio and the diverse lines we develop for each market.",
            ["product.size"] = "Larger caliber",
            ["product.flavor"] = "Exceptional taste",
            ["product.pack"] = "Premium presentation",
            ["product.btnMore"] = "LEARN MORE",
            ["product.featuredVarieties"] = "FEATURED VARIETIES",
            ["product.linePrefix"] = "Line",
            ["product.countOption"] = "option",
            ["product.countLines"] = "lines",
            ["product.quickView"] = "View commercial details",

            // Product Lines
            ["line.clasica"] = "Classic",
            ["line.big-delight"] = "Big Delight",
            ["line.organica"] = "Organic",
            ["line.legacy"] = "Legacy",
            ["line.legacy-jumbo"] = "Legacy Jumbo Blues",

            // Products data
            ["prod.clasica-arandanos.desc"] = "Firm fruit with balanced flavor, crisp texture, and reliable year-round quality.",
            ["prod.clasica-arandanos.size"] = "Uniform caliber (14mm - 16mm)",
            ["prod.clasica-arandanos.flavor"] = "Balanced flavor",
            ["prod.clasica-arandanos.pack"] = "Retail clamshell presentation",
            ["prod.clasica-arandanos.shelf"] = "21 days refrigerated",

            ["prod.big-delight-arandanos.desc"] = "A larger, more prominent and detailed experience. Hand-selected blueberries for those seeking something truly exceptional.",
            ["prod.big-delight-arandanos.size"] = "Jumbo caliber (18mm - 24mm)",
            ["prod.big-delight-arandanos.flavor"] = "Exceptional sweet and aromatic flavor",
            ["prod.big-delight-arandanos.pack"] = "100% recyclable premium rPET presentation",
            ["prod.big-delight-arandanos.shelf"] = "24 days refrigerated",

            ["prod.clasica-frambuesas.desc"] = "The perfect harmony of color, texture, and delicate flavor for a naturally versatile fruit.",
            ["prod.clasica-frambuesas.size"] = "Standard caliber (14mm - 16mm)",
            ["prod.clasica-frambuesas.flavor"] = "Delicate sweet-tart flavor",
            ["prod.clasica-frambuesas.pack"] = "Ventilated 170g clamshell",
            ["prod.clasica-frambuesas.shelf"] = "14 days refrigerated",

            ["prod.clasica-zarzamoras.desc"] = "Deep flavor, lustrous appearance, and peak freshness for culinary recipes, snacking, and daily enjoyment.",
            ["prod.clasica-zarzamoras.size"] = "Standard caliber (15mm - 18mm)",
            ["prod.clasica-zarzamoras.flavor"] = "Intense, fruity flavor",
            ["prod.clasica-zarzamoras.pack"] = "170g / 340g clamshell",
            ["prod.clasica-zarzamoras.shelf"] = "15 days refrigerated",

            ["prod.clasica-fresas.desc"] = "A familiar, vibrant, naturally sweet fruit crafted for families and premium grocery displays.",
            ["prod.clasica-fresas.size"] = "Uniform medium to large caliber",
            ["prod.clasica-fresas.flavor"] = "Naturally sweet and aromatic",
            ["prod.clasica-fresas.pack"] = "454g (1 lb) & 907g (2 lb) clamshell",
            ["prod.clasica-fresas.shelf"] = "12 days refrigerated",

            ["prod.organica-arandanos.desc"] = "Harvested without synthetic chemicals, utilizing agroecological practices that protect soil vitality and natural cycles.",
            ["prod.organica-arandanos.size"] = "Certified organic caliber",
            ["prod.organica-arandanos.flavor"] = "Pure natural sweetness",
            ["prod.organica-arandanos.pack"] = "100% recyclable rPET clamshell",
            ["prod.organica-arandanos.shelf"] = "20 days refrigerated",

            ["prod.organica-frambuesas.desc"] = "Cultivated without synthetic fertilizers, honoring regenerative agriculture and environmental balance.",
            ["prod.organica-frambuesas.size"] = "Premium caliber (16mm+)",
            ["prod.organica-frambuesas.flavor"] = "Pure wild sweetness",
            ["prod.organica-frambuesas.pack"] = "Compostable fiber Bio-Pack",
            ["prod.organica-frambuesas.shelf"] = "16 days refrigerated",

            ["prod.organica-zarzamoras.desc"] = "Cultivated with regenerative organic standards, preserving deep rich flavor and soil microbiology.",
            ["prod.organica-zarzamoras.size"] = "Select organic caliber",
            ["prod.organica-zarzamoras.flavor"] = "Deep berry undertones",
            ["prod.organica-zarzamoras.pack"] = "Ventilated recyclable clamshell",
            ["prod.organica-zarzamoras.shelf"] = "15 days refrigerated",

            ["prod.legacy-arandanos.desc"] = "Our signature varietal line: superior genetics that deliver deeper flavor, intense color, and unmatched crunch.",
            ["prod.legacy-arandanos.size"] = "Selected superior genetics",
            ["prod.legacy-arandanos.flavor"] = "Intense, consistent flavor profile",
            ["prod.legacy-arandanos.pack"] = "Exclusive Legacy presentation",
            ["prod.legacy-arandanos.shelf"] = "25 days refrigerated",

            ["prod.legacy-jumbo.desc"] = "The pinnacle of colossal blueberries, combining calibers exceeding 22mm with unforgettable acoustic crunch.",
            ["prod.legacy-jumbo.size"] = "Colossal caliber (> 22mm)",
            ["prod.legacy-jumbo.flavor"] = "Concentrated sweetness with acoustic pop",
            ["prod.legacy-jumbo.pack"] = "Ventilated premium clamshell",
            ["prod.legacy-jumbo.shelf"] = "28 days refrigerated",

            // Genetics Section
            ["genetics.kicker"] = "PATENTED VARIETAL PROGRAM",
            ["genetics.title1"] = "PREMIUM",
            ["genetics.title2"] = "GENETICS",
            ["genetics.subtitle"] = "Behind every berry lies obsession with detail: from superior genetic selection to gentle hand-harvesting for simply perfect fruit.",
            ["genetics.btnCatalog"] = "Explore varietal catalog",
            ["genetics.registered"] = "REGISTERED VARIETY",
            ["genetics.btnSheet"] = "View technical sheet",
            ["genetics.sheetTitle"] = "Agronomic Technical Sheet",
            ["genetics.specCaliber"] = "Caliber",
            ["genetics.specBrix"] = "Brix Sweetness",
            ["genetics.specFirmness"] = "Firmness",
            ["genetics.specShelf"] = "Shelf Life",
            ["genetics.specHarvest"] = "Harvest Window",
            ["genetics.specLicensing"] = "Licensing",
            ["genetics.btnInquire"] = "Request Harvest Program",
            ["genetics.type.raspberry"] = "Raspberry",
            ["genetics.type.blackberry"] = "Blackberry",
            ["genetics.type.blueberry"] = "Blueberry",
            ["genetics.type.strawberry"] = "Strawberry",

            ["genetics.amalia.desc"] = "Registered variety featuring uniform ripening that ensures consistent export-grade quality. Its sturdy closed receptacle prevents postharvest collapse.",
            ["genetics.amalia.t1"] = "Uniform maturity",
            ["genetics.amalia.t2"] = "Consistent caliber",
            ["genetics.amalia.t3"] = "Low chill requirement",
            ["genetics.amalia.t4"] = "High export yield",
            ["genetics.amalia.shelf"] = "18+ days",
            ["genetics.amalia.harvest"] = "October - May",
            ["genetics.amalia.license"] = "Exclusive Berries Paradise Patent",

            ["genetics.erendira.desc"] = "High-performing Mexican variety bred for local climates, offering an extraordinary sensory profile and thorn-free canes.",
            ["genetics.erendira.t1"] = "Climate resistance",
            ["genetics.erendira.t2"] = "Extended harvest window",
            ["genetics.erendira.t3"] = "Distinct aromatic profile",
            ["genetics.erendira.t4"] = "Regional adaptability",
            ["genetics.erendira.shelf"] = "20+ days",
            ["genetics.erendira.harvest"] = "November - June",
            ["genetics.erendira.license"] = "National Protected Variety",

            ["genetics.sekoya-beauty.desc"] = "Exceptional blueberry variety with preserved natural bloom, crunchy texture, and persistent jumbo caliber, tailor-made for international luxury retail.",
            ["genetics.sekoya-beauty.t1"] = "Deep blue color",
            ["genetics.sekoya-beauty.t2"] = "Pristine bloom",
            ["genetics.sekoya-beauty.t3"] = "Superior firmness",
            ["genetics.sekoya-beauty.t4"] = "Culinary versatility",
            ["genetics.sekoya-beauty.shelf"] = "25+ days",
            ["genetics.sekoya-beauty.harvest"] = "September - March",
            ["genetics.sekoya-beauty.license"] = "Sekoya™ Club Member Variety",

            ["genetics.sekoya-pop.desc"] = "Premium blueberry variety crafted for high-demand international markets, with optimal sweet-acid balance and signature acoustic 'pop' on the bite.",
            ["genetics.sekoya-pop.t1"] = "Exceptional taste",
            ["genetics.sekoya-pop.t2"] = "Uniform sizing",
            ["genetics.sekoya-pop.t3"] = "Extended shelf life",
            ["genetics.sekoya-pop.t4"] = "High field yield",
            ["genetics.sekoya-pop.shelf"] = "30+ days",
            ["genetics.sekoya-pop.harvest"] = "November - May",
            ["genetics.sekoya-pop.license"] = "Sekoya™ Club Member Variety",

            // Field to World
            ["field.kicker"] = "END-TO-END ORIGIN TRACEABILITY",
            ["field.title1"] = "FIELD TO",
            ["field.title2"] = "WORLD",
            ["field.subtitle"] = "A rigorous process guaranteeing freshness, quality, and consistency at every stage.",
            ["field.btnProtocols"] = "View Safety Protocols",
            ["field.stage"] = "STAGE",
            ["field.btnVideo"] = "Watch Origin Video",

            ["field.step.1.title"] = "Cultivation",
            ["field.step.1.sub"] = "Precision plant nutrition & ideal microclimates",
            ["field.step.1.desc"] = "Farms located in sheltered Jalisco and Michoacán highland valleys above 1,500m. Computerized drip irrigation, balanced organic nutrition, and native bumblebee pollination.",
            ["field.step.1.high"] = "100% lab-tested deep well water",
            ["field.step.1.temp"] = "18°C - 24°C ambient",

            ["field.step.2.title"] = "Harvest",
            ["field.step.2.sub"] = "Expert dawn hand-harvesting",
            ["field.step.2.desc"] = "Hand-picked during the cool early hours of the morning when berries retain their natural turgor. Gently handled by the stem to preserve the waxy protective bloom intact.",
            ["field.step.2.high"] = "100% artisanal hand-picking",
            ["field.step.2.temp"] = "12°C - 16°C morning",

            ["field.step.3.title"] = "Selection & Packing",
            ["field.step.3.sub"] = "Spectral optical grading & cleanrooms",
            ["field.step.3.desc"] = "In positive-pressure cleanrooms with filtered air, 360° computer vision spectral cameras inspect millimetric size, color, Brix, and firmness at up to 12 tons per hour.",
            ["field.step.3.high"] = "360° spectral computer vision",
            ["field.step.3.temp"] = "10°C packhouse controlled",

            ["field.step.4.title"] = "Cold Chain",
            ["field.step.4.sub"] = "Forced-air rapid thermal shock tunnels",
            ["field.step.4.desc"] = "Within 60 minutes of picking, fruit enters forced-air tunnels pulling metabolic field heat down to precisely 1.5°C, sealing in natural sugars and arresting cellular aging.",
            ["field.step.4.high"] = "Thermal reduction to 1.5°C in < 60 min",
            ["field.step.4.temp"] = "1.0°C - 2.0°C uninterrupted",

            ["field.step.5.title"] = "To the World",
            ["field.step.5.sub"] = "Express multimodal land & air logistics",
            ["field.step.5.desc"] = "Direct refrigerated shipments to over 19 nations. Express ground logistics to the US and Canada, plus direct air cargo flights to Europe, Japan, Singapore, and the UAE.",
            ["field.step.5.high"] = "Global retail arrival in < 48 hrs",
            ["field.step.5.temp"] = "Continuous cold chain at 1.5°C",

            // Quality Section
            ["quality.kicker"] = "AGRICULTURAL SCIENCE & COLD CHAIN",
            ["quality.title1"] = "EXCELLENCE",
            ["quality.title2"] = "& QUALITY",
            ["quality.subtitle"] = "Millimetric climate and handling control from pollination to destination retail shelf.",
            ["quality.cert"] = "PrimusGFS Certification",
            ["quality.certSub"] = "Global Grade AA Audits",
            ["quality.btnTech"] = "Quality Technical Sheet",
            ["quality.controlStandard"] = "Control Standard",
            ["quality.thermalParam"] = "Thermal Parameter",
            ["quality.btnHarvestTimeline"] = "View Harvest Timeline",
            ["quality.capacity"] = "Capacity:",
            ["quality.temperature"] = "Temperature:",
            ["quality.processOf"] = "PROCESS {0} OF 05",
            ["quality.btnCert"] = "Check Food Safety Certifications",

            ["quality.fac.1.title"] = "Field",
            ["quality.fac.1.sub"] = "Fertile Valleys",
            ["quality.fac.1.desc"] = "Over 3,000 hectares under protected macro-tunnels with real-time satellite weather tracking and on-site meteorological telemetry.",
            ["quality.fac.1.high"] = "3,000+ Hectares",
            ["quality.fac.1.temp"] = "Ambient",

            ["quality.fac.2.title"] = "Pre-Cooling",
            ["quality.fac.2.sub"] = "Shock Tunnels",
            ["quality.fac.2.desc"] = "Counter-flow forced-air pre-cooling tunnels with 95% relative humidity control to prevent moisture loss.",
            ["quality.fac.2.high"] = "80 Tons / Shift",
            ["quality.fac.2.temp"] = "1.5°C",

            ["quality.fac.3.title"] = "Selection & Packing",
            ["quality.fac.3.sub"] = "Automated Lines",
            ["quality.fac.3.desc"] = "Automated optical sorting lines with multispectral cameras scanning for sub-millimeter microscopic imperfections.",
            ["quality.fac.3.high"] = "120 Tons / Day",
            ["quality.fac.3.temp"] = "10°C",

            ["quality.fac.4.title"] = "Storage",
            ["quality.fac.4.sub"] = "Smart Cold Rooms",
            ["quality.fac.4.desc"] = "Refrigerated chambers with catalytic ethylene scrubbers and ozonated atmosphere to preserve berry vitality.",
            ["quality.fac.4.high"] = "500 Static Pallets",
            ["quality.fac.4.temp"] = "1.0°C - 1.5°C",

            ["quality.fac.5.title"] = "Shipping",
            ["quality.fac.5.sub"] = "Refrigerated Fleet",
            ["quality.fac.5.desc"] = "Cloud-connected smart reefer trucks and containers with 0.5°C variance sensors and live telemetry.",
            ["quality.fac.5.high"] = "40+ Daily Loads",
            ["quality.fac.5.temp"] = "1.5°C",

            // Recipes Section
            ["recipes.kicker"] = "INSPIRATION",
            ["recipes.title1"] = "BERRY",
            ["recipes.title2"] = "RECIPES",
            ["recipes.subtitle"] = "\"Fluffy, flavorful, with the perfect harmony of sweetness and crisp tartness.\"",
            ["recipes.btnAll"] = "VIEW ALL RECIPES",
            ["recipes.editorial"] = "CULINARY EDITORIAL",
            ["recipes.btnView"] = "VIEW RECIPE",
            ["recipes.servings"] = "Servings",
            ["recipes.persons"] = "servings",
            ["recipes.calories"] = "Calories",
            ["recipes.ingredients"] = "Ingredients",
            ["recipes.freshItems"] = "fresh items",
            ["recipes.freshIngredients"] = "Fresh Ingredients",
            ["recipes.prep"] = "Prep",
            ["recipes.cook"] = "Cook",
            ["recipes.stepByStep"] = "Step by Step",
            ["recipes.btnReady"] = "Ready to cook!",
            ["recipes.prev"] = "Previous recipe",
            ["recipes.next"] = "Next recipe",

            ["recipe.pancakes-berries-mixtos.title"] = "Mixed Berry Pancakes",
            ["recipe.pancakes-berries-mixtos.cat"] = "Breakfast",
            ["recipe.pancakes-berries-mixtos.desc"] = "Fluffy, flavorful, with the perfect harmony of sweetness and crisp tartness. Topped with freshly harvested berries and warm maple syrup.",

            ["recipe.smoothie-bowl-antioxidante.title"] = "Super Berry Smoothie Bowl",
            ["recipe.smoothie-bowl-antioxidante.cat"] = "Energy & Health",
            ["recipe.smoothie-bowl-antioxidante.desc"] = "A concentrated bowl of polyphenols, fiber, and natural antioxidants to kickstart your day with vitality and freshness.",

            ["recipe.tartaleta-frambuesas-crema-mascarpone.title"] = "Raspberry & Mascarpone Tartlet",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.cat"] = "Fine Pastry",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.desc"] = "Crispy sablée crust filled with velvety vanilla mascarpone whipped cream, crowned with fresh Amalia® raspberries.",

            ["recipe.parfait-arandanos-chia-granola.title"] = "Chia, Yogurt & Blueberry Parfait",
            ["recipe.parfait-arandanos-chia-granola.cat"] = "Light Breakfast",
            ["recipe.parfait-arandanos-chia-granola.desc"] = "Alternating layers of coconut milk chia pudding, unsweetened Greek yogurt, and rustic jumbo blueberry compote.",

            ["recipe.cheesecake-zarzamora-legacy.title"] = "Baked Blackberry Cheesecake",
            ["recipe.cheesecake-zarzamora-legacy.cat"] = "Gourmet Desserts",
            ["recipe.cheesecake-zarzamora-legacy.desc"] = "Silky water-bath baked cheesecake topped with a glossy Legacy blackberry glaze and bright lemon zest.",

            ["recipe.ensalada-fresas-espinaca-queso-cabra.title"] = "Spinach, Strawberry & Walnut Salad",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.cat"] = "Fresh Lunch",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.desc"] = "Vibrant freshly sliced strawberries over tender baby spinach, aged goat cheese medallions, and aged Modena balsamic reduction.",

            ["recipe.muffins-avena-arandanos-limon.title"] = "Rustic Oat & Blueberry Muffins",
            ["recipe.muffins-avena-arandanos-limon.cat"] = "Healthy Snack",
            ["recipe.muffins-avena-arandanos-limon.desc"] = "Refined sugar-free baked oat muffins bursting with whole blueberries for juicy natural sweetness in every bite.",

            ["recipe.galette-rustica-multi-berries.title"] = "Rustic Triple Berry Galette",
            ["recipe.galette-rustica-multi-berries.cat"] = "Rustic Bakery",
            ["recipe.galette-rustica-multi-berries.desc"] = "Freeform flaky golden crust wrapping a baked medley of raspberries, blueberries, and blackberries with raw demerara sugar.",

            // Global Presence
            ["presence.kicker"] = "GLOBAL REACH",
            ["presence.title1"] = "GLOBAL",
            ["presence.title2"] = "PRESENCE",
            ["presence.subtitle"] = "\"Delivering premier berries to discerning markets across the world.\"",
            ["presence.btnExport"] = "Export Program",
            ["presence.skus"] = "Retail SKUs",
            ["presence.skusSub"] = "Clamshell and bulk shelf-ready formats",
            ["presence.countries"] = "Export destination countries",
            ["presence.countriesSub"] = "North America, Europe, Asia-Pacific, and Middle East",
            ["presence.global"] = "Global markets",
            ["presence.globalSub"] = "Strategic commercial distribution across 4 continents",
            ["presence.markets"] = "Markets",
            ["map.mexico"] = "MEXICO",
            ["map.usa_canada"] = "USA & CANADA",
            ["map.europe"] = "EUROPE",
            ["map.south_america"] = "SOUTH AMERICA",
            ["map.asia_pacific"] = "ASIA-PACIFIC",
            ["map.middle_east"] = "MIDDLE EAST",

            // Final CTA
            ["cta.kicker"] = "THE CONCLUSION OF AN EXTRAORDINARY JOURNEY",
            ["cta.title1"] = "WE DELIVER QUALITY BERRIES",
            ["cta.title2"] = "TO YOUR MARKET",
            ["cta.subtitle"] = "\"Looking for a dependable supply chain partner?\"",
            ["cta.btnProducts"] = "VIEW PRODUCTS",
            ["cta.btnSales"] = "CONTACT SALES",

            // Footer
            ["footer.slogan"] = "Berries Grown with Purpose.",
            ["footer.language"] = "LANGUAGE:",
            ["footer.privacy"] = "Privacy Policy",
            ["footer.terms"] = "Terms of Service",
            ["footer.colProducts"] = "PRODUCTS",
            ["footer.colCompany"] = "COMPANY",
            ["footer.colHelp"] = "HELP",
            ["footer.colSocial"] = "SOCIAL",
            ["footer.blueberries"] = "Blueberries",
            ["footer.raspberries"] = "Raspberries",
            ["footer.blackberries"] = "Blackberries",
            ["footer.strawberries"] = "Strawberries",
            ["footer.quality"] = "Excellence & Quality",
            ["footer.about"] = "About Us",
            ["footer.inspiration"] = "Inspiration",
            ["footer.contact"] = "Contact",
            ["footer.faqs"] = "FAQs",
            ["footer.copyright"] = "©2026 Berries Paradise. All rights reserved.",

            // Modals General
            ["modal.close"] = "Close",
            ["common.close"] = "Close",
            ["modal.product.size"] = "Larger size",
            ["modal.product.flavor"] = "Flavor",
            ["modal.product.pack"] = "Presentation",
            ["modal.product.formatsTitle"] = "Commercial & Retail Formats",
            ["modal.product.formatsText"] = "Available in 6 oz, 11 oz, 18 oz clamshells and master carton for temperature-controlled air and ocean export.",
            ["modal.product.disclaimer"] = "Available for international import",
            ["modal.product.btnQuote"] = "Quote this product",

            ["modal.berry.nutritionTitle"] = "Nutritional Profile & Health",
            ["modal.berry.seasonLabel"] = "Season:",
            ["modal.berry.qualityTitle"] = "Quality Standards & Attributes",
            ["modal.berry.btnQuote"] = "Quote Retail Program",

            ["modal.contact.title"] = "Contact Sales & Distribution",
            ["modal.contact.titleMain"] = "Contact",
            ["modal.contact.titleHighlight"] = "Sales & Distribution",
            ["modal.contact.subtitle"] = "Connect directly with our export team for retail programs, wholesale, and global supply.",
            ["modal.contact.fullName"] = "Full Name *",
            ["modal.contact.placeholderName"] = "e.g. Robert Smith",
            ["modal.contact.company"] = "Company / Retailer *",
            ["modal.contact.placeholderCompany"] = "e.g. Whole Foods / Costco",
            ["modal.contact.email"] = "Corporate Email *",
            ["modal.contact.destinationCountry"] = "Destination Country *",
            ["modal.contact.productInterest"] = "Product of Interest",
            ["modal.contact.estimatedVolume"] = "Estimated Volume",
            ["modal.contact.specs"] = "Requirement Specifications",
            ["modal.contact.placeholderSpecs"] = "Specify sizes, clamshell packaging type, or delivery schedule...",
            ["modal.contact.submit"] = "Submit Export Inquiry",
            ["modal.contact.successTitle"] = "Inquiry Received!",
            ["modal.contact.successText"] = "A Berries Paradise commercial director will reach out within 24 hours with our quotation catalog and availability.",
            ["modal.contact.btnReset"] = "Got it",

            ["modal.video.title"] = "Berries Grown with Purpose: Harvesting the Future",
            ["modal.video.desc"] = "Cinematic journey through our protected fields, varietal genetic innovation, and cold chain international traceability.",
            ["modal.video.download"] = "Download",
            ["modal.video.contact"] = "Contact Sales",
            ["modal.video.unmute"] = "Unmute Audio",
            ["modal.video.error"] = "Could not initialize direct video playback.",
            ["modal.video.newTab"] = "Watch video in new tab ↗",

            ["modal.search.title"] = "Search in Berries Paradise",
            ["modal.search.placeholder"] = "Type a product, genetics, or recipe (e.g. Big Delight, Sekoya, Pancakes)...",
            ["modal.search.noResults"] = "No results found for your search.",
            ["modal.search.products"] = "Products",
            ["modal.search.genetics"] = "Varietal Genetics",
            ["modal.search.recipes"] = "Recipes"
        },
        ["FR"] = new()
        {
            // Navigation
            ["nav.products"] = "Produits",
            ["nav.quality"] = "Excellence & Qualité",
            ["nav.process"] = "Du Champ au Monde",
            ["nav.genetics"] = "Génétique",
            ["nav.inspiration"] = "Inspiration",
            ["nav.contact"] = "Contact",
            ["nav.productos"] = "Produits",
            ["nav.calidad"] = "Excellence & Qualité",
            ["nav.proceso"] = "Du Champ au Monde",
            ["nav.genetica"] = "Génétique",
            ["nav.inspiracion"] = "Inspiration",
            ["nav.contacto"] = "Contact",
            ["nav.cta"] = "Contacter les Ventes",
            ["nav.search"] = "Rechercher dans le catalogue",

            // Hero
            ["hero.eyebrow"] = "UN AVENIR PLUS FRAIS",
            ["hero.title1"] = "BAIES",
            ["hero.title2"] = "CULTIVÉES AVEC",
            ["hero.title3"] = "ENGAGEMENT.",
            ["hero.description"] = "Des baies d'exception pour un monde plus sain, savoureux et durable.",
            ["hero.btnExplore"] = "EXPLORER LES PRODUITS",
            ["hero.btnStory"] = "DÉCOUVRIR NOTRE HISTOIRE",
            ["hero.btnVideo"] = "VOIR LA VIDÉO",

            // Berries Section
            ["berries.kicker"] = "PORTFOLIO FRAIS & DURABLE",
            ["berries.title1"] = "NOS",
            ["berries.title2"] = "BAIES",
            ["berries.subtitle"] = "Un assortiment frais, polyvalent et débordant de saveurs.",
            ["berries.btnPortfolio"] = "Voir le catalogue",
            ["berries.btnMore"] = "En savoir plus",
            ["berries.badge"] = "Variété Sélecte",
            ["berries.availability"] = "Disponibilité",
            ["berries.benefit"] = "Bénéfice Clé",
            ["berries.btnSheet"] = "Fiche Technique Complète",

            // Fruits
            ["fruit.arandanos"] = "Myrtilles",
            ["fruit.frambuesas"] = "Framboises",
            ["fruit.zarzamoras"] = "Mûres",
            ["fruit.fresas"] = "Fraises",
            ["fruit.all"] = "Toutes",

            // Fruit Details
            ["berry.arandanos.name"] = "Myrtilles",
            ["berry.arandanos.desc"] = "Fruit ferme, à la saveur équilibrée, texture remarquable, pruine naturelle préservée et qualité constante toute l'année.",
            ["berry.arandanos.season"] = "Production continue 52 semaines par an",
            ["berry.arandanos.health"] = "Riche en anthocyanes, flavonoïdes bioactifs, vitamine C (16% VJR), vitamine K (36% VJR) et manganèse protecteur.",
            ["berry.arandanos.c1"] = "Calibres standard à Jumbo (14mm - 26mm)",
            ["berry.arandanos.c2"] = "Pruine protectrice naturelle intacte",
            ["berry.arandanos.c3"] = "Fermeté supérieure à 220 g/mm",
            ["berry.arandanos.c4"] = "Brix équilibré 12,0° - 15,5°",

            ["berry.frambuesas.name"] = "Framboises",
            ["berry.frambuesas.desc"] = "L'équilibre parfait d'une couleur rubis, d'une texture veloutée et d'un arôme délicat pour un fruit naturellement polyvalent.",
            ["berry.frambuesas.season"] = "Septembre à Juin (Pic en hiver et printemps)",
            ["berry.frambuesas.health"] = "Source exceptionnelle de fibres alimentaires (8g par tasse), acide ellagique, vitamine C (54% VJR) et antioxydants.",
            ["berry.frambuesas.c1"] = "Réceptacle fermé résistant",
            ["berry.frambuesas.c2"] = "Couleur rouge rubis éclatante",
            ["berry.frambuesas.c3"] = "Acidité équilibrée et douceur naturelle",
            ["berry.frambuesas.c4"] = "Durée de conservation réfrigérée jusqu'à 18 jours",

            ["berry.zarzamoras.name"] = "Mûres",
            ["berry.zarzamoras.desc"] = "Saveur intense, drupéoles charnues au brillant noir profond et fraîcheur incomparable pour la gastronomie et le snacking sain.",
            ["berry.zarzamoras.season"] = "Octobre à Mai",
            ["berry.zarzamoras.health"] = "Excellent apport en vitamine C, vitamine K, folate et lutéine pour la protection oculaire et immunitaire.",
            ["berry.zarzamoras.c1"] = "Variétés cultivées 100% sans épines",
            ["berry.zarzamoras.c2"] = "Zéro régression rouge (red drupelet)",
            ["berry.zarzamoras.c3"] = "Douceur pure sans amertume",
            ["berry.zarzamoras.c4"] = "Calibre large et régulier",

            ["berry.fresas.name"] = "Fraises",
            ["berry.fresas.desc"] = "Un fruit vibrant et parfumé, à la douceur naturelle, récolté à maturité optimale pour régaler toute la famille.",
            ["berry.fresas.season"] = "Novembre à Mai",
            ["berry.fresas.health"] = "Apporte plus de 140% de l'apport journalier recommandé en vitamine C par portion, favorisant vitalité et collagène.",
            ["berry.fresas.c1"] = "Forme conique homogène",
            ["berry.fresas.c2"] = "Rouge carmin du cœur à la peau",
            ["berry.fresas.c3"] = "Brillant naturel sans cires chimiques",
            ["berry.fresas.c4"] = "Calibre sélectionné pour la grande distribution",

            // Products Section
            ["product.kicker"] = "PORTFOLIO PRODUITS",
            ["product.title1"] = "NOTRE PORTFOLIO,",
            ["product.title2"] = "NOS BAIES.",
            ["product.subtitle"] = "Découvrez notre gamme de baies et les différentes sélections que nous développons pour chaque marché.",
            ["product.size"] = "Calibre supérieur",
            ["product.flavor"] = "Saveur remarquable",
            ["product.pack"] = "Présentation haut de gamme",
            ["product.btnMore"] = "EN SAVOIR PLUS",
            ["product.featuredVarieties"] = "VARIÉTÉS VEDETTES",
            ["product.linePrefix"] = "Gamme",
            ["product.countOption"] = "option",
            ["product.countLines"] = "lignes",
            ["product.quickView"] = "Voir les détails commerciaux",

            // Product Lines
            ["line.clasica"] = "Classique",
            ["line.big-delight"] = "Big Delight",
            ["line.organica"] = "Biologique",
            ["line.legacy"] = "Legacy",
            ["line.legacy-jumbo"] = "Legacy Jumbo Blues",

            // Products data
            ["prod.clasica-arandanos.desc"] = "Fruit ferme, à la saveur équilibrée, texture croquante et qualité constante toute l'année.",
            ["prod.clasica-arandanos.size"] = "Calibre uniforme (14mm - 16mm)",
            ["prod.clasica-arandanos.flavor"] = "Saveur équilibrée",
            ["prod.clasica-arandanos.pack"] = "Format barquette retail",
            ["prod.clasica-arandanos.shelf"] = "21 jours réfrigéré",

            ["prod.big-delight-arandanos.desc"] = "Une expérience d'un calibre supérieur, remarquable en rayon. Myrtilles sélectionnées à la main pour les plus exigeants.",
            ["prod.big-delight-arandanos.size"] = "Calibre jumbo (18mm - 24mm)",
            ["prod.big-delight-arandanos.flavor"] = "Saveur sucrée et aromatique exceptionnelle",
            ["prod.big-delight-arandanos.pack"] = "Barquette premium rPET 100% recyclable",
            ["prod.big-delight-arandanos.shelf"] = "24 jours réfrigéré",

            ["prod.clasica-frambuesas.desc"] = "L'harmonie parfaite de couleur, texture et douceur délicate pour un fruit naturellement polyvalent.",
            ["prod.clasica-frambuesas.size"] = "Calibre standard (14mm - 16mm)",
            ["prod.clasica-frambuesas.flavor"] = "Saveur délicate douce-acidulée",
            ["prod.clasica-frambuesas.pack"] = "Barquette ventilée 170g",
            ["prod.clasica-frambuesas.shelf"] = "14 jours réfrigéré",

            ["prod.clasica-zarzamoras.desc"] = "Saveur intense, robe sombre et fraîcheur optimale pour la pâtisserie, les encas sains et le quotidien.",
            ["prod.clasica-zarzamoras.size"] = "Calibre standard (15mm - 18mm)",
            ["prod.clasica-zarzamoras.flavor"] = "Saveur fruitée profonde",
            ["prod.clasica-zarzamoras.pack"] = "Barquette 170g / 340g",
            ["prod.clasica-zarzamoras.shelf"] = "15 jours réfrigéré",

            ["prod.clasica-fresas.desc"] = "Un fruit familier, éclatant et naturellement sucré pensé pour le partage et les rayons primeurs.",
            ["prod.clasica-fresas.size"] = "Calibre régulier moyen à grand",
            ["prod.clasica-fresas.flavor"] = "Naturellement sucré et parfumé",
            ["prod.clasica-fresas.pack"] = "Barquette 454g (1 lb) et 907g (2 lb)",
            ["prod.clasica-fresas.shelf"] = "12 jours réfrigéré",

            ["prod.organica-arandanos.desc"] = "Récoltées sans intrants chimiques synthétiques, selon des pratiques préservant la vie des sols et les cycles naturels.",
            ["prod.organica-arandanos.size"] = "Calibre certifié biologique",
            ["prod.organica-arandanos.flavor"] = "Douceur pure naturelle",
            ["prod.organica-arandanos.pack"] = "Barquette rPET 100% recyclable",
            ["prod.organica-arandanos.shelf"] = "20 jours réfrigéré",

            ["prod.organica-frambuesas.desc"] = "Cultivées sans engrais synthétiques, dans le respect de l'agriculture biologique régénératrice.",
            ["prod.organica-frambuesas.size"] = "Calibre supérieur (16mm+)",
            ["prod.organica-frambuesas.flavor"] = "Douceur sauvage authentique",
            ["prod.organica-frambuesas.pack"] = "Bio-Pack en fibre compostable",
            ["prod.organica-frambuesas.shelf"] = "16 jours réfrigéré",

            ["prod.organica-zarzamoras.desc"] = "Cultivées selon des normes biologiques rigoureuses, préservant la richesse aromatique naturelle.",
            ["prod.organica-zarzamoras.size"] = "Calibre bio sélectionné",
            ["prod.organica-zarzamoras.flavor"] = "Notes de fruits noirs intenses",
            ["prod.organica-zarzamoras.pack"] = "Barquette recyclable ventilée",
            ["prod.organica-zarzamoras.shelf"] = "15 jours réfrigéré",

            ["prod.legacy-arandanos.desc"] = "Notre sélection variétale d'élite : une génétique d'exception offrant une saveur plus profonde, un croquant et une tenue parfaits.",
            ["prod.legacy-arandanos.size"] = "Génétique supérieure sélectionnée",
            ["prod.legacy-arandanos.flavor"] = "Saveur intense et constante",
            ["prod.legacy-arandanos.pack"] = "Présentation exclusive Legacy",
            ["prod.legacy-arandanos.shelf"] = "25 jours réfrigéré",

            ["prod.legacy-jumbo.desc"] = "L'apogée des myrtilles de taille colossale, combinant des calibres supérieurs à 22mm à un croquant inoubliable.",
            ["prod.legacy-jumbo.size"] = "Calibre colossal (> 22mm)",
            ["prod.legacy-jumbo.flavor"] = "Douceur concentrée avec pop sonore",
            ["prod.legacy-jumbo.pack"] = "Barquette ventilée haut de gamme",
            ["prod.legacy-jumbo.shelf"] = "28 jours réfrigéré",

            // Genetics Section
            ["genetics.kicker"] = "PROGRAMME VARIÉTAL BREVETÉ",
            ["genetics.title1"] = "GÉNÉTIQUE",
            ["genetics.title2"] = "PREMIUM",
            ["genetics.subtitle"] = "Derrière chaque baie réside le souci du détail : du choix des meilleures sélections génétiques à la récolte manuelle.",
            ["genetics.btnCatalog"] = "Explorer le catalogue variétal",
            ["genetics.registered"] = "VARIÉTÉ ENREGISTRÉE",
            ["genetics.btnSheet"] = "Voir la fiche technique",
            ["genetics.sheetTitle"] = "Fiche Technique Agronomique",
            ["genetics.specCaliber"] = "Calibre",
            ["genetics.specBrix"] = "Douceur Brix",
            ["genetics.specFirmness"] = "Fermeté",
            ["genetics.specShelf"] = "Durée de Conservation",
            ["genetics.specHarvest"] = "Période de Récolte",
            ["genetics.specLicensing"] = "Licence",
            ["genetics.btnInquire"] = "Demander un Programme de Récolte",
            ["genetics.type.raspberry"] = "Framboise",
            ["genetics.type.blackberry"] = "Mûre",
            ["genetics.type.blueberry"] = "Myrtille",
            ["genetics.type.strawberry"] = "Fraise",

            ["genetics.amalia.desc"] = "Variété enregistrée à maturation homogène garantissant des lots uniformes de première classe pour l'export. Son réceptacle fermé évite l'affaissement après récolte.",
            ["genetics.amalia.t1"] = "Maturité uniforme",
            ["genetics.amalia.t2"] = "Calibre constant",
            ["genetics.amalia.t3"] = "Faible besoin de froid",
            ["genetics.amalia.t4"] = "Taux d'exportation élevé",
            ["genetics.amalia.shelf"] = "18+ jours",
            ["genetics.amalia.harvest"] = "Octobre - Mai",
            ["genetics.amalia.license"] = "Brevet Exclusif Berries Paradise",

            ["genetics.erendira.desc"] = "Variété mexicaine à haut rendement développée pour les climats locaux, offrant un profil aromatique remarquable et des plants dépourvus d'épines.",
            ["genetics.erendira.t1"] = "Résistance climatique",
            ["genetics.erendira.t2"] = "Récolte prolongée",
            ["genetics.erendira.t3"] = "Profil aromatique unique",
            ["genetics.erendira.t4"] = "Adaptabilité régionale",
            ["genetics.erendira.shelf"] = "20+ jours",
            ["genetics.erendira.harvest"] = "Novembre - Juin",
            ["genetics.erendira.license"] = "Variété Protégée Nationale",

            ["genetics.sekoya-beauty.desc"] = "Myrtille d'une beauté exceptionnelle avec pruine naturelle préservée, texture croquante et calibre jumbo régulier, idéale pour le retail mondial haut de gamme.",
            ["genetics.sekoya-beauty.t1"] = "Bleu profond éclatant",
            ["genetics.sekoya-beauty.t2"] = "Pruine parfaite",
            ["genetics.sekoya-beauty.t3"] = "Fermeté supérieure",
            ["genetics.sekoya-beauty.t4"] = "Polyvalence culinaire",
            ["genetics.sekoya-beauty.shelf"] = "25+ jours",
            ["genetics.sekoya-beauty.harvest"] = "Septembre - Mars",
            ["genetics.sekoya-beauty.license"] = "Sekoya™ Club Member Variety",

            ["genetics.sekoya-pop.desc"] = "Variété premium de myrtilles élaborée pour les marchés d'excellence, avec équilibre sucre-acidité optimal et son fameux éclat croquant sous la dent.",
            ["genetics.sekoya-pop.t1"] = "Saveur remarquable",
            ["genetics.sekoya-pop.t2"] = "Calibre homogène",
            ["genetics.sekoya-pop.t3"] = "Longue tenue en rayon",
            ["genetics.sekoya-pop.t4"] = "Haute productivité",
            ["genetics.sekoya-pop.shelf"] = "30+ jours",
            ["genetics.sekoya-pop.harvest"] = "Novembre - Mai",
            ["genetics.sekoya-pop.license"] = "Sekoya™ Club Member Variety",

            // Field to World
            ["field.kicker"] = "TRAÇABILITÉ TOTALE À LA SOURCE",
            ["field.title1"] = "DU CHAMP",
            ["field.title2"] = "AU MONDE",
            ["field.subtitle"] = "Un processus exigeant garantissant fraîcheur, pureté et consistance.",
            ["field.btnProtocols"] = "Protocoles de Salubrité",
            ["field.stage"] = "ÉTAPE",
            ["field.btnVideo"] = "Voir la Vidéo d'Origine",

            ["field.step.1.title"] = "Culture",
            ["field.step.1.sub"] = "Nutrition végétale de précision & microclimats d'altitude",
            ["field.step.1.desc"] = "Parcelles situées dans les vallées abritées de Jalisco et Michoacán à plus de 1 500 m d'altitude. Irrigation informatisée au goutte-à-goutte, fertilisation organique et pollinisation naturelle par des bourdons locaux.",
            ["field.step.1.high"] = "100% eau de forage profond contrôlée",
            ["field.step.1.temp"] = "18°C - 24°C ambiant",

            ["field.step.2.title"] = "Récolte",
            ["field.step.2.sub"] = "Cueillette manuelle experte dès l'aube",
            ["field.step.2.desc"] = "Récoltée à la main aux heures fraîches du matin lorsque le fruit conserve sa turgescence naturelle. Maniée par la tige pour préserver la pruine protectrice intacte.",
            ["field.step.2.high"] = "Cueillette artisanale 100% manuelle",
            ["field.step.2.temp"] = "12°C - 16°C matinal",

            ["field.step.3.title"] = "Sélection & Emballage",
            ["field.step.3.sub"] = "Tri optique spectral en salles blanches",
            ["field.step.3.desc"] = "En salles à pression positive et air filtré, des caméras spectrales 360° analysent le calibre millimétrique, la colorimétrie, le brix et la texture jusqu'à 12 tonnes par heure.",
            ["field.step.3.high"] = "Vision spectrale 360° par ordinateur",
            ["field.step.3.temp"] = "10°C en salles de conditionnement",

            ["field.step.4.title"] = "Chaîne du Froid",
            ["field.step.4.sub"] = "Tunnels de choc thermique par air pulsé",
            ["field.step.4.desc"] = "En moins de 60 minutes après cueillette, les baies entrent en tunnels d'air forcé abaissant la température à 1,5°C précis, scellant les sucres et stoppant le vieillissement.",
            ["field.step.4.high"] = "Baisse thermique à 1,5°C en < 60 min",
            ["field.step.4.temp"] = "1,0°C - 2,0°C ininterrompu",

            ["field.step.5.title"] = "Vers le Monde",
            ["field.step.5.sub"] = "Logistique express multimodale terrestre & aérienne",
            ["field.step.5.desc"] = "Expéditions directes sous température dirigée vers plus de 19 pays. Acheminement routier express vers les USA et le Canada, et vols directs vers l'Europe, le Japon, Singapour et les Émirats.",
            ["field.step.5.high"] = "Arrivée en rayon international en < 48h",
            ["field.step.5.temp"] = "Chaîne du froid continue à 1,5°C",

            // Quality Section
            ["quality.kicker"] = "SCIENCE AGRICOLE & CHAÎNE DU FROID",
            ["quality.title1"] = "EXCELLENCE",
            ["quality.title2"] = "& QUALITÉ",
            ["quality.subtitle"] = "Contrôle millimétrique de la pollinisation au rayon de distribution.",
            ["quality.cert"] = "Certification PrimusGFS",
            ["quality.certSub"] = "Audits Mondiaux Grade AA",
            ["quality.btnTech"] = "Fiche Technique Qualité",
            ["quality.controlStandard"] = "Norme de Contrôle",
            ["quality.thermalParam"] = "Paramètre Thermique",
            ["quality.btnHarvestTimeline"] = "Voir la Chronologie de Récolte",
            ["quality.capacity"] = "Capacité :",
            ["quality.temperature"] = "Température :",
            ["quality.processOf"] = "PROCESSUS {0} SUR 05",
            ["quality.btnCert"] = "Consulter les Certifications de Salubrité",

            ["quality.fac.1.title"] = "Champ",
            ["quality.fac.1.sub"] = "Vallées Fertiles",
            ["quality.fac.1.desc"] = "Plus de 3 000 hectares sous macro-tunnels avec suivi météo par satellite et stations télémétriques dédiées.",
            ["quality.fac.1.high"] = "3 000+ Hectares",
            ["quality.fac.1.temp"] = "Ambiant",

            ["quality.fac.2.title"] = "Pré-refroidissement",
            ["quality.fac.2.sub"] = "Tunnels de Choc",
            ["quality.fac.2.desc"] = "Tunnels de pré-refroidissement à air pulsé à contre-courant avec humidité relative maintenue à 95%.",
            ["quality.fac.2.high"] = "80 T / Poste",
            ["quality.fac.2.temp"] = "1,5°C",

            ["quality.fac.3.title"] = "Sélection & Emballage",
            ["quality.fac.3.sub"] = "Lignes Automatisées",
            ["quality.fac.3.desc"] = "Lignes de calibrage optique automatisées équipées de caméras multispectrales décelant les défauts microscopiques.",
            ["quality.fac.3.high"] = "120 T / Jour",
            ["quality.fac.3.temp"] = "10°C",

            ["quality.fac.4.title"] = "Stockage",
            ["quality.fac.4.sub"] = "Chambres Intelligentes",
            ["quality.fac.4.desc"] = "Chambres froides à absorption d'éthylène et atmosphère ozonée préservant l'énergie des fruits.",
            ["quality.fac.4.high"] = "500 Palettes statiques",
            ["quality.fac.4.temp"] = "1,0°C - 1,5°C",

            ["quality.fac.5.title"] = "Expédition",
            ["quality.fac.5.sub"] = "Flotte Réfrigérée",
            ["quality.fac.5.desc"] = "Camions et conteneurs frigorifiques connectés au cloud avec alertes de variation de température à 0,5°C près.",
            ["quality.fac.5.high"] = "40+ Chargements / Jour",
            ["quality.fac.5.temp"] = "1,5°C",

            // Recipes Section
            ["recipes.kicker"] = "INSPIRATION",
            ["recipes.title1"] = "RECETTES",
            ["recipes.title2"] = "AUX BAIES",
            ["recipes.subtitle"] = "\"Moelleux, savoureux et avec l'équilibre parfait entre douceur et fraîcheur.\"",
            ["recipes.btnAll"] = "TOUTES LES RECETTES",
            ["recipes.editorial"] = "ÉDITORIAL CULINAIRE",
            ["recipes.btnView"] = "DÉCOUVRIR LA RECETTE",
            ["recipes.servings"] = "Portions",
            ["recipes.persons"] = "personnes",
            ["recipes.calories"] = "Calories",
            ["recipes.ingredients"] = "Ingrédients",
            ["recipes.freshItems"] = "ingrédients frais",
            ["recipes.freshIngredients"] = "Ingrédients Frais",
            ["recipes.prep"] = "Prép",
            ["recipes.cook"] = "Cuisson",
            ["recipes.stepByStep"] = "Étape par Étape",
            ["recipes.btnReady"] = "Prêt à cuisiner !",
            ["recipes.prev"] = "Recette précédente",
            ["recipes.next"] = "Recette suivante",

            ["recipe.pancakes-berries-mixtos.title"] = "Pancakes aux Baies Mélangées",
            ["recipe.pancakes-berries-mixtos.cat"] = "Petit-Déjeuner",
            ["recipe.pancakes-berries-mixtos.desc"] = "Moelleux, savoureux et avec l'équilibre parfait entre douceur et fraîcheur. Couronné de baies fraîchement cueillies et de sirop d'érable tiède.",

            ["recipe.smoothie-bowl-antioxidante.title"] = "Super Smoothie Bowl aux Baies",
            ["recipe.smoothie-bowl-antioxidante.cat"] = "Énergie & Santé",
            ["recipe.smoothie-bowl-antioxidante.desc"] = "Un concentré de polyphénols, de fibres et d'antioxydants naturels pour démarrer la journée avec vitalité et fraîcheur.",

            ["recipe.tartaleta-frambuesas-crema-mascarpone.title"] = "Tartelette aux Framboises & Mascarpone",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.cat"] = "Pâtisserie Fine",
            ["recipe.tartaleta-frambuesas-crema-mascarpone.desc"] = "Pâte sablée croustillante garnie d'une crème fouettée au mascarpone et vanille, surmontée de framboises fraîches Amalia®.",

            ["recipe.parfait-arandanos-chia-granola.title"] = "Parfait de Chia, Yaourt & Myrtilles",
            ["recipe.parfait-arandanos-chia-granola.cat"] = "Petit-Déjeuner Léger",
            ["recipe.parfait-arandanos-chia-granola.desc"] = "Couches alternées de pudding de chia au lait de coco, yaourt grec nature et compotée rustique de grosses myrtilles.",

            ["recipe.cheesecake-zarzamora-legacy.title"] = "Cheesecake Cuit aux Mûres",
            ["recipe.cheesecake-zarzamora-legacy.cat"] = "Desserts Gourmet",
            ["recipe.cheesecake-zarzamora-legacy.desc"] = "Texture crémeuse cuite au bain-marie, nappée d'un coulis brillant de mûres Legacy et de zeste de citron.",

            ["recipe.ensalada-fresas-espinaca-queso-cabra.title"] = "Salade d'Épinards, Fraises & Noix",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.cat"] = "Déjeuner Frais",
            ["recipe.ensalada-fresas-espinaca-queso-cabra.desc"] = "Fraîcheur des fraises émincées sur jeunes pousses d'épinards, médaillons de chèvre cendré et réduction balsamique de Modène.",

            ["recipe.muffins-avena-arandanos-limon.title"] = "Muffins Rustiques Avoine & Myrtilles",
            ["recipe.muffins-avena-arandanos-limon.cat"] = "Encas Sain",
            ["recipe.muffins-avena-arandanos-limon.desc"] = "Muffins à l'avoine sans sucre raffiné, regorgeant de myrtilles entières éclatant à la cuisson pour une douceur juteuse.",

            ["recipe.galette-rustica-multi-berries.title"] = "Galette Rustique aux Trois Baies",
            ["recipe.galette-rustica-multi-berries.cat"] = "Boulangerie Rustique",
            ["recipe.galette-rustica-multi-berries.desc"] = "Pâte feuilletée croustillante pliée à la main renfermant une explosion de framboises, myrtilles et mûres cuites au sucre muscovado.",

            // Global Presence
            ["presence.kicker"] = "RAYONNEMENT MONDIAL",
            ["presence.title1"] = "PRÉSENCE",
            ["presence.title2"] = "MONDIALE",
            ["presence.subtitle"] = "\"Nous livrons des baies d'excellence aux marchés les plus exigeants.\"",
            ["presence.btnExport"] = "Programme d'Exportation",
            ["presence.skus"] = "Formats Retail",
            ["presence.skusSub"] = "Clamshells et vrac prêts pour les rayons",
            ["presence.countries"] = "Pays de destination",
            ["presence.countriesSub"] = "Amérique du Nord, Europe, Asie-Pacifique et Moyen-Orient",
            ["presence.global"] = "Marchés mondiaux",
            ["presence.globalSub"] = "Partenariats commerciaux sur 4 continents",
            ["presence.markets"] = "Marchés",
            ["map.mexico"] = "MEXIQUE",
            ["map.usa_canada"] = "USA & CANADA",
            ["map.europe"] = "EUROPE",
            ["map.south_america"] = "AMÉRIQUE DU SUD",
            ["map.asia_pacific"] = "ASIE-PACIFIQUE",
            ["map.middle_east"] = "MOYEN-ORIENT",

            // Final CTA
            ["cta.kicker"] = "L'APOGÉE D'UN VOYAGE EXTRAORDINAIRE",
            ["cta.title1"] = "NOUS LIVRONS DES BAIES DE QUALITÉ",
            ["cta.title2"] = "À VOTRE MARCHÉ",
            ["cta.subtitle"] = "\"À la recherche d'un partenaire fiable pour votre chaîne d'approvisionnement ?\"",
            ["cta.btnProducts"] = "VOIR LES PRODUITS",
            ["cta.btnSales"] = "CONTACTER LES VENTES",

            // Footer
            ["footer.slogan"] = "Berries Grown with Purpose.",
            ["footer.language"] = "LANGUE :",
            ["footer.privacy"] = "Politique de confidentialité",
            ["footer.terms"] = "Conditions d'utilisation",
            ["footer.colProducts"] = "PRODUITS",
            ["footer.colCompany"] = "ENTREPRISE",
            ["footer.colHelp"] = "AIDE",
            ["footer.colSocial"] = "RÉSEAUX",
            ["footer.blueberries"] = "Myrtilles",
            ["footer.raspberries"] = "Framboises",
            ["footer.blackberries"] = "Mûres",
            ["footer.strawberries"] = "Fraises",
            ["footer.quality"] = "Excellence & Qualité",
            ["footer.about"] = "À propos",
            ["footer.inspiration"] = "Inspiration",
            ["footer.contact"] = "Contact",
            ["footer.faqs"] = "FAQ",
            ["footer.copyright"] = "©2026 Berries Paradise. Tous droits réservés.",

            // Modals General
            ["modal.close"] = "Fermer",
            ["common.close"] = "Fermer",
            ["modal.product.size"] = "Calibre supérieur",
            ["modal.product.flavor"] = "Saveur",
            ["modal.product.pack"] = "Présentation",
            ["modal.product.formatsTitle"] = "Formats Commerciaux & Retail",
            ["modal.product.formatsText"] = "Disponible en barquettes clamshell de 6 oz, 11 oz, 18 oz et carton master pour l'export maritime et aérien sous température dirigée.",
            ["modal.product.disclaimer"] = "Disponible pour l'importation internationale",
            ["modal.product.btnQuote"] = "Demander un devis",

            ["modal.berry.nutritionTitle"] = "Profil Nutritionnel & Santé",
            ["modal.berry.seasonLabel"] = "Saison :",
            ["modal.berry.qualityTitle"] = "Normes & Attributs de Qualité",
            ["modal.berry.btnQuote"] = "Demander un Programme Retail",

            ["modal.contact.title"] = "Contacter les Ventes & Distribution",
            ["modal.contact.titleMain"] = "Contacter",
            ["modal.contact.titleHighlight"] = "Ventes & Distribution",
            ["modal.contact.subtitle"] = "Contactez directement notre équipe d'exportation pour les programmes retail, vente en gros et approvisionnement mondial.",
            ["modal.contact.fullName"] = "Nom Complet *",
            ["modal.contact.placeholderName"] = "ex. Robert Martin",
            ["modal.contact.company"] = "Entreprise / Distributeur *",
            ["modal.contact.placeholderCompany"] = "ex. Carrefour / Costco",
            ["modal.contact.email"] = "E-mail Professionnel *",
            ["modal.contact.destinationCountry"] = "Pays de Destination *",
            ["modal.contact.productInterest"] = "Produit Recherché",
            ["modal.contact.estimatedVolume"] = "Volume Estimé",
            ["modal.contact.specs"] = "Spécifications de la Demande",
            ["modal.contact.placeholderSpecs"] = "Précisez les calibres, type de barquette ou calendrier de livraison...",
            ["modal.contact.submit"] = "Envoyer la Demande aux Exportations",
            ["modal.contact.successTitle"] = "Demande Reçue !",
            ["modal.contact.successText"] = "Un directeur commercial de Berries Paradise prendra contact avec vous sous 24 heures avec nos tarifs et disponibilités.",
            ["modal.contact.btnReset"] = "Compris",

            ["modal.video.title"] = "Berries Grown with Purpose : Récolter l'Avenir",
            ["modal.video.desc"] = "Voyage cinématographique à travers nos serres protégées, notre innovation génétique et notre chaîne du froid internationale.",
            ["modal.video.download"] = "Télécharger",
            ["modal.video.contact"] = "Contacter les Ventes",
            ["modal.video.unmute"] = "Activer le Son",
            ["modal.video.error"] = "Impossible d'initialiser la lecture vidéo directe.",
            ["modal.video.newTab"] = "Regarder la vidéo dans un nouvel onglet ↗",

            ["modal.search.title"] = "Rechercher dans Berries Paradise",
            ["modal.search.placeholder"] = "Recherchez un produit, une variété ou une recette (ex. Big Delight, Sekoya, Pancakes)...",
            ["modal.search.noResults"] = "Aucun résultat trouvé pour votre recherche.",
            ["modal.search.products"] = "Produits",
            ["modal.search.genetics"] = "Génétique Variétale",
            ["modal.search.recipes"] = "Recettes"
        }
    };

    public string T(string key, string? lang = null)
    {
        var targetLang = string.IsNullOrWhiteSpace(lang) ? "ES" : lang.Trim().ToUpperInvariant();
        if (Translations.TryGetValue(targetLang, out var dict) && dict.TryGetValue(key, out var val))
        {
            return val;
        }
        if (Translations["ES"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }
        return key;
    }
}
